<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GM.EntityFramework.Domain" Version="1.2.1" />
        <PackageReference Include="GM.Messaging" Version="1.2.0" />
        <PackageReference Include="GM.Notifications.Domain" Version="1.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="BoundedContext\MessageBoundedContext\" />
    </ItemGroup>

</Project>
